include:
  package:lint/analysis_options_package.yaml

  # ------ List of linting rules    ----- #
  #  https://dart-lang.github.io/linter/lints/index.html
  #  https://pub.dev/packages/lint
  # ------------------------------------- #

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: true

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Good packages document everything
    public_member_api_docs: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    parameter_assignments: true

# ------ Analyze errors behavior  ----- #
#  Options value: ignore | info | warning | error
# ------------------------------------- #

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - lib/**/**/**.g.dart
  errors:
    parameter_assignments: error
