name: sophon
description: A new Flutter project.
publish_to: 'none' 
version: 3.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  intl: ^0.20.2
  nuxify_widgetbook_core:
    git:
      url: https://github.com/Nuxify/widgetbook.git
      path: core
      ref: v1.7.2
  # Mobile Scanner widget
  # nuxify_widgetbook_qr_scanner:
  #     git:
  #       url: https://github.com/Nuxify/widgetbook.git
  #       path: qr_scanner
  #       ref: v1.7.2
  reown_appkit: ^1.4.3+1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  web3dart: ^2.7.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  lint: ^2.8.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/core/infrastructures/contracts/staging/greeter.abi.json
    - assets/images/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-launcher-icon.png"
  remove_alpha_ios: true
  
flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png

  web: false

  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    image: assets/images/logo-android12.png