name: sophon
description: A new Flutter project.
publish_to: 'none' 
version: 2.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  eth_sig_util: ^0.0.9
  external_app_launcher: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.2.9
  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  nuxify_widgetbook:
    git:
      url: git@github.com:Nuxify/widgetbook.git
      ref: release/1.0.0
  pointycastle: ^3.1.1
  url_launcher: ^6.2.3
  walletconnect_dart: ^0.0.11
  web3auth_flutter: ^3.0.0
  web3dart: ^2.7.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  lint: ^2.3.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/metamask-logo.png
    - assets/images/google-logo.png
    - assets/images/walletconnect-logo.png
    - lib/contracts/staging/greeter.abi.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
