name: sophon
description: A new Flutter project.
publish_to: 'none' 
version: 2.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_fadein: ^2.0.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  nuxify_widgetbook:
    git:
      url: git@github.com:Nuxify/widgetbook.git
      ref: release/1.0.0
  shimmer: ^3.0.0
  web3auth_flutter: ^3.0.0
  web3dart: ^2.7.1
  web3modal_flutter: ^3.2.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  lint: ^2.3.0
  mocktail: ^1.0.1


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/contracts/staging/greeter.abi.json
    - assets/images/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 800
          
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-launcher-icon.png"
  remove_alpha_ios: true
